# Generated by Django 5.0.6 on 2026-10-05 15:52

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepaymentSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_number', models.PositiveIntegerField()),
                ('scheduled_date', models.DateField(db_index=True)),
                ('principal_portion', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_portion', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fees_portion', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('waived', 'Waived')], db_index=True, default='pending', max_length=20)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_schedule', to='loans.loan')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repayment_schedules', to='accounts.organisation')),
            ],
            options={
                'db_table': 'repayment_schedules',
                'ordering': ['loan', 'period_number'],
            },
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('actual_date', models.DateField()),
                ('method', models.CharField(choices=[('debit_order', 'Debit Order'), ('eft', 'EFT'), ('card', 'Card'), ('cash', 'Cash'), ('adjustment', 'Adjustment')], default='debit_order', max_length=20)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='successful', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loans.loan')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='accounts.organisation')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repayments', to='repayments.repaymentschedule')),
            ],
            options={
                'db_table': 'repayments',
                'ordering': ['-actual_date'],
            },
        ),
        migrations.AddIndex(
            model_name='repaymentschedule',
            index=models.Index(fields=['loan', 'status'], name='repayment_s_loan_id_1ebab1_idx'),
        ),
        migrations.AddIndex(
            model_name='repaymentschedule',
            index=models.Index(fields=['scheduled_date', 'status'], name='repayment_s_schedul_98e7fa_idx'),
        ),
        migrations.AddIndex(
            model_name='repaymentschedule',
            index=models.Index(fields=['organisation', 'status'], name='repayment_s_organis_c7f623_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='repaymentschedule',
            unique_together={('loan', 'period_number')},
        ),
        migrations.AddIndex(
            model_name='repayment',
            index=models.Index(fields=['loan', 'status'], name='repayments_loan_id_931507_idx'),
        ),
        migrations.AddIndex(
            model_name='repayment',
            index=models.Index(fields=['organisation', 'status'], name='repayments_organis_50005d_idx'),
        ),
    ]
