# Generated by Django 5.0.6 on 2026-10-05 15:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProcessor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('processor_type', models.CharField(choices=[('ai', 'AI Provider'), ('payment', 'Payment Provider'), ('credit_bureau', 'Credit Bureau'), ('storage', 'Storage / Cloud'), ('email', 'Email'), ('sms', 'SMS'), ('monitoring', 'Monitoring'), ('analytics', 'Analytics'), ('other', 'Other')], db_index=True, max_length=30)),
                ('country', models.CharField(default='South Africa', max_length=100)),
                ('is_cross_border', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('contract_reference', models.CharField(blank=True, max_length=255)),
                ('contract_signed_at', models.DateField(blank=True, null=True)),
                ('contract_expires_at', models.DateField(blank=True, db_index=True, null=True)),
                ('data_categories', models.JSONField(blank=True, default=list, help_text='List of data categories shared with this processor.')),
                ('cross_border_justification', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'compliance_data_processors',
                'ordering': ['processor_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompliancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('category', models.CharField(choices=[('popia', 'POPIA'), ('paia', 'PAIA'), ('nca', 'National Credit Act'), ('fica', 'FICA / AML'), ('data_retention', 'Data Retention'), ('information_security', 'Information Security'), ('complaints', 'Complaints Procedure'), ('responsible_lending', 'Responsible Lending'), ('other', 'Other')], db_index=True, max_length=40)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('superseded', 'Superseded'), ('retired', 'Retired')], db_index=True, default='draft', max_length=20)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('next_review_date', models.DateField(blank=True, db_index=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_policies', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_policies', to='documents.document')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_policies',
                'ordering': ['category', '-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('popia', 'POPIA'), ('paia', 'PAIA'), ('nca', 'National Credit Act'), ('fica', 'FICA / AML'), ('data_retention', 'Data Retention'), ('information_security', 'Information Security'), ('complaints', 'Complaints Procedure'), ('responsible_lending', 'Responsible Lending'), ('other', 'Other')], db_index=True, max_length=40)),
                ('frequency', models.CharField(choices=[('once', 'One-off'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-annual'), ('annual', 'Annual'), ('biennial', 'Every two years')], default='annual', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('done', 'Done'), ('overdue', 'Overdue'), ('not_applicable', 'Not applicable')], db_index=True, default='pending', max_length=20)),
                ('due_date', models.DateField(db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('evidence', models.TextField(blank=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_compliance_tasks', to=settings.AUTH_USER_MODEL)),
                ('evidence_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_tasks', to='documents.document')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_compliance_tasks', to=settings.AUTH_USER_MODEL)),
                ('related_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_tasks', to='compliance.compliancepolicy')),
            ],
            options={
                'db_table': 'compliance_tasks',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='DataSubjectRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requestor_name', models.CharField(max_length=200)),
                ('requestor_email', models.EmailField(max_length=254)),
                ('requestor_phone', models.CharField(blank=True, max_length=20)),
                ('request_type', models.CharField(choices=[('access', 'Access to data'), ('correction', 'Correction of data'), ('deletion', 'Deletion of data'), ('objection', 'Objection to processing'), ('portability', 'Portability'), ('withdraw_consent', 'Withdraw consent')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('received', 'Received'), ('in_progress', 'In progress'), ('awaiting_verification', 'Awaiting verification'), ('completed', 'Completed'), ('refused', 'Refused'), ('withdrawn', 'Withdrawn')], db_index=True, default='received', max_length=30)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sla_due_at', models.DateTimeField(db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('request_details', models.TextField()),
                ('response_notes', models.TextField(blank=True)),
                ('refusal_reason', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_dsars', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_subject_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_data_subject_requests',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('incident_type', models.CharField(choices=[('data_breach', 'Data breach'), ('unauthorised_access', 'Unauthorised access'), ('system_compromise', 'System compromise'), ('malware', 'Malware / ransomware'), ('phishing', 'Phishing / social engineering'), ('insider_threat', 'Insider threat'), ('denial_of_service', 'Denial of service'), ('physical', 'Physical security'), ('other', 'Other')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('contained', 'Contained'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('affected_systems', models.JSONField(blank=True, default=list)),
                ('affected_records_count', models.PositiveIntegerField(default=0)),
                ('affected_data_categories', models.JSONField(blank=True, default=list)),
                ('requires_notification', models.BooleanField(default=False)),
                ('regulator_notified_at', models.DateTimeField(blank=True, null=True)),
                ('subjects_notified_at', models.DateTimeField(blank=True, null=True)),
                ('contained_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('root_cause', models.TextField(blank=True)),
                ('remediation', models.TextField(blank=True)),
                ('prevention_notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_security_incidents',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.AddIndex(
            model_name='compliancepolicy',
            index=models.Index(fields=['category', 'status'], name='compliance__categor_94fbd0_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancepolicy',
            index=models.Index(fields=['next_review_date'], name='compliance__next_re_4d5123_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancetask',
            index=models.Index(fields=['status', 'due_date'], name='compliance__status_a494cb_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancetask',
            index=models.Index(fields=['category', 'status'], name='compliance__categor_4770b6_idx'),
        ),
        migrations.AddIndex(
            model_name='datasubjectrequest',
            index=models.Index(fields=['status', 'sla_due_at'], name='compliance__status_ae64b6_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['status', 'severity'], name='compliance__status_42bd2b_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['requires_notification', 'regulator_notified_at'], name='compliance__require_e5e0d0_idx'),
        ),
    ]
