# Generated by Django 5.0.6 on 2026-10-05 15:52

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitInstruction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='mock', max_length=50)),
                ('provider_reference', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('account_holder_name', models.CharField(max_length=200)),
                ('account_number_last4', models.CharField(blank=True, default='', max_length=4)),
                ('account_number_encrypted', models.TextField(blank=True, default='')),
                ('bank_name', models.CharField(max_length=100)),
                ('branch_code', models.CharField(blank=True, default='', max_length=20)),
                ('account_type', models.CharField(blank=True, default='cheque', max_length=20)),
                ('mandate_reference', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('mandate_reference_number', models.CharField(blank=True, default='', max_length=64)),
                ('mandate_signed_at', models.DateTimeField(blank=True, null=True)),
                ('mandate_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('mandate_user_agent', models.TextField(blank=True, default='')),
                ('mandate_pdf_storage_key', models.CharField(blank=True, default='', max_length=500)),
                ('mandate_hash', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_client', 'Awaiting Client Signature'), ('pending_review', 'Pending Staff Review'), ('active', 'Active'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='draft', max_length=25)),
                ('is_active', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('bank_account', models.ForeignKey(blank=True, help_text='Structured bank account this mandate was created from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mandates', to='accounts.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mandates', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_instructions', to='loans.loan')),
                ('mandate_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_mandates', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debit_instructions', to='accounts.organisation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_mandates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'debit_instructions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repayment_schedule_id', models.UUIDField(blank=True, null=True)),
                ('provider', models.CharField(default='mock', max_length=50)),
                ('provider_transaction_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('idempotency_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('successful', 'Successful'), ('failed', 'Failed'), ('reversed', 'Reversed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('debit_order', 'Debit Order'), ('eft', 'EFT'), ('card', 'Card'), ('cash', 'Cash')], default='debit_order', max_length=20)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('attempt_number', models.PositiveSmallIntegerField(default=1, help_text='1 = first attempt; >1 = retry.')),
                ('is_undisputable', models.BooleanField(db_index=True, default=False, help_text='Set by admin: retry via the irrevocable mandate authority.')),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, help_text='When the retry should next be attempted.', null=True)),
                ('retry_reason', models.TextField(blank=True, default='')),
                ('decline_code', models.CharField(blank=True, default='', max_length=50)),
                ('decline_reason', models.TextField(blank=True, default='')),
                ('retry_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('debit_instruction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.debitinstruction')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='loans.loan')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='accounts.organisation')),
                ('parent_transaction', models.ForeignKey(blank=True, help_text='Original attempt this retry was created from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='payments.paymenttransaction')),
                ('retry_scheduled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_retries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=50)),
                ('webhook_type', models.CharField(blank=True, default='', max_length=100)),
                ('provider_event_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('signature', models.CharField(blank=True, default='', max_length=255)),
                ('processed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhooks', to='payments.paymenttransaction')),
            ],
            options={
                'db_table': 'payment_webhooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('actual_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('missing', 'Missing'), ('partial', 'Partial'), ('overpayment', 'Overpayment'), ('unmatched', 'Unmatched'), ('reversed', 'Reversed')], db_index=True, max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_records', to='loans.loan')),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymenttransaction')),
            ],
            options={
                'db_table': 'reconciliation_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='debitinstruction',
            index=models.Index(fields=['loan', 'status'], name='debit_instr_loan_id_3edf7a_idx'),
        ),
        migrations.AddIndex(
            model_name='debitinstruction',
            index=models.Index(fields=['provider', 'provider_reference'], name='debit_instr_provide_8d270f_idx'),
        ),
        migrations.AddIndex(
            model_name='debitinstruction',
            index=models.Index(fields=['status', 'created_at'], name='debit_instr_status_9e2a8a_idx'),
        ),
        migrations.AddIndex(
            model_name='debitinstruction',
            index=models.Index(fields=['organisation', 'status'], name='debit_instr_organis_95f49a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['loan', 'status'], name='payment_tra_loan_id_98026c_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['provider', 'provider_transaction_id'], name='payment_tra_provide_0544ff_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status', 'next_retry_at'], name='payment_tra_status_772c50_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['organisation', 'status'], name='payment_tra_organis_79533e_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentwebhook',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_event_id__gt', '')), fields=('provider', 'provider_event_id'), name='unique_provider_event'),
        ),
        migrations.AddIndex(
            model_name='reconciliationrecord',
            index=models.Index(fields=['loan', 'status'], name='reconciliat_loan_id_e2a8a0_idx'),
        ),
    ]
