# Generated by Django 5.0.6 on 2026-10-05 15:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffordabilityAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gross_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monthly_expenses', models.DecimalField(decimal_places=2, max_digits=15)),
                ('existing_debt_obligations', models.DecimalField(decimal_places=2, max_digits=15)),
                ('proposed_repayment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(max_length=30)),
                ('explanation', models.TextField(blank=True)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affordability_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'affordability_assessments',
                'ordering': ['-created_at'],
            },
        ),
    ]
