# Generated by Django 5.0.6 on 2026-10-05 15:52

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_interest', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('fees_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('term_periods', models.PositiveIntegerField()),
                ('repayment_frequency', models.CharField(default='monthly', max_length=20)),
                ('collection_day', models.PositiveSmallIntegerField(blank=True, help_text='Day of month (1-31) for repayments. Set by admin.', null=True)),
                ('collection_window_start', models.PositiveSmallIntegerField(blank=True, help_text='Day of month (1-31) collection attempts begin.', null=True)),
                ('collection_window_end', models.PositiveSmallIntegerField(blank=True, help_text='Day of month (1-31) collection attempts stop.', null=True)),
                ('max_retry_attempts', models.PositiveSmallIntegerField(default=3, help_text='Maximum undisputable retry attempts per instalment.')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('defaulted', 'Defaulted')], default='pending', max_length=20)),
                ('default_risk_score', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='0-100 score; higher = higher likelihood of default')),
                ('default_risk_band', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='low', max_length=20)),
                ('default_risk_updated_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='accounts.organisation')),
            ],
            options={
                'db_table': 'loans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('pdf_storage_key', models.CharField(max_length=500)),
                ('agreement_hash', models.CharField(help_text='SHA-256 of PDF', max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Client'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('accepted_user_agent', models.TextField(blank=True, default='')),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='loans.loan')),
            ],
            options={
                'db_table': 'loan_agreements',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('requested_term', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('document_review', 'Document Review'), ('kyc_review', 'KYC Review'), ('affordability_review', 'Affordability Review'), ('credit_review', 'Credit Review'), ('approved', 'Approved'), ('contract_pending', 'Contract Pending'), ('contract_accepted', 'Contract Accepted'), ('disbursement_pending', 'Disbursement Pending'), ('active', 'Active'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('defaulted', 'Defaulted'), ('restructured', 'Restructured'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=30)),
                ('kyc_status_snapshot', models.CharField(blank=True, default='', max_length=30)),
                ('affordability_result', models.JSONField(blank=True, null=True)),
                ('credit_review_notes', models.TextField(blank=True)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('approved_term', models.PositiveIntegerField(blank=True, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('policy_result', models.JSONField(blank=True, help_text='Cached output of the deterministic policy engine.', null=True)),
                ('policy_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('client_payday', models.PositiveSmallIntegerField(blank=True, help_text='Day of month (1-31) the client gets paid', null=True)),
                ('documents_reviewed', models.BooleanField(default=False)),
                ('transactions_reviewed', models.BooleanField(default=False)),
                ('contract_verified_by_admin', models.BooleanField(default=False)),
                ('contract_verified_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to=settings.AUTH_USER_MODEL)),
                ('contract_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_contracts', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='accounts.organisation')),
            ],
            options={
                'db_table': 'loan_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='loans.loanapplication'),
        ),
        migrations.CreateModel(
            name='LoanApplicationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='loans.loanapplication')),
            ],
            options={
                'db_table': 'loan_application_events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=15)),
                ('max_amount', models.DecimalField(decimal_places=2, default=Decimal('100000.00'), max_digits=15)),
                ('min_term', models.PositiveIntegerField(default=1)),
                ('max_term', models.PositiveIntegerField(default=60)),
                ('interest_type', models.CharField(choices=[('flat', 'Flat'), ('simple', 'Simple'), ('amortized', 'Amortized')], default='flat', max_length=20)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=6)),
                ('origination_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('2.50'), max_digits=5)),
                ('late_payment_fee', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=15)),
                ('repayment_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly')], default='monthly', max_length=20)),
                ('max_exposure', models.DecimalField(decimal_places=2, default=Decimal('1000000.00'), max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('eligibility_rules', models.JSONField(blank=True, default=dict)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_products', to='accounts.organisation')),
            ],
            options={
                'db_table': 'loan_products',
            },
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='loans.loanproduct'),
        ),
        migrations.AddField(
            model_name='loan',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.loanproduct'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['client', 'status'], name='loan_applic_client__7e2fe3_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['status', 'created_at'], name='loan_applic_status_0684b2_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['organisation', 'status'], name='loan_applic_organis_92386a_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['client', 'status'], name='loans_client__fdc042_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['organisation', 'status'], name='loans_organis_15d868_idx'),
        ),
    ]
