# Generated by Django 5.0.6 on 2026-10-05 15:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=50, unique=True)),
                ('api_key_encrypted', models.TextField(blank=True, default='')),
                ('model_name', models.CharField(max_length=100)),
                ('max_tokens', models.PositiveIntegerField(default=2000)),
                ('temperature', models.DecimalField(decimal_places=2, default=0.1, max_digits=3)),
                ('is_active', models.BooleanField(default=False)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('usage_limit', models.PositiveIntegerField(default=1000)),
            ],
            options={
                'db_table': 'ai_provider_configurations',
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('input_reference', models.CharField(blank=True, max_length=255)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('explanation', models.TextField(blank=True)),
                ('human_reviewed', models.BooleanField(default=False)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAffordabilityAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verdict', models.CharField(choices=[('likely_to_pay', 'Likely to Pay'), ('at_risk', 'At Risk'), ('unlikely_to_pay', 'Unlikely to Pay'), ('insufficient_data', 'Insufficient Data')], max_length=30)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('risk_factors', models.JSONField(blank=True, default=list)),
                ('positive_factors', models.JSONField(blank=True, default=list)),
                ('recommended_max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('recommended_term_months', models.PositiveIntegerField(blank=True, null=True)),
                ('dti_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('disposable_income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('staff_override_verdict', models.CharField(blank=True, default='', max_length=30)),
                ('staff_notes', models.TextField(blank=True, default='')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_affordability_assessments', to='loans.loanapplication')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_affordability_assessments', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ai_assessments', to=settings.AUTH_USER_MODEL)),
                ('ai_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_affordability_assessments', to='ai.aianalysis')),
            ],
            options={
                'db_table': 'ai_affordability_assessments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['application', '-created_at'], name='ai_affordab_applica_901ca2_idx'), models.Index(fields=['verdict'], name='ai_affordab_verdict_803b7a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClientInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headline', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Informational'), ('positive', 'Positive'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('category', models.CharField(default='general', max_length=50)),
                ('action_label', models.CharField(blank=True, default='', max_length=80)),
                ('action_url', models.CharField(blank=True, default='', max_length=300)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('ai_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_insights', to='ai.aianalysis')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_insights',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'is_dismissed', '-created_at'], name='client_insi_client__c70e28_idx'), models.Index(fields=['severity'], name='client_insi_severit_6ea407_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClientTrendSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('monthly_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('debt_obligations', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('disposable_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('active_loans_count', models.PositiveIntegerField(default=0)),
                ('total_outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('payments_on_time', models.PositiveIntegerField(default=0)),
                ('payments_late', models.PositiveIntegerField(default=0)),
                ('payments_missed', models.PositiveIntegerField(default=0)),
                ('avg_days_late', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('affordability_score', models.PositiveIntegerField(default=0)),
                ('trend_direction', models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('deteriorating', 'Deteriorating')], default='stable', max_length=20)),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('ai_recommendation', models.CharField(blank=True, default='', max_length=30)),
                ('raw_ai_output', models.JSONField(blank=True, default=dict)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_trend_snapshots',
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['client', '-snapshot_date'], name='client_tren_client__a510eb_idx'), models.Index(fields=['trend_direction'], name='client_tren_trend_d_ce966a_idx')],
                'unique_together': {('client', 'snapshot_date')},
            },
        ),
    ]
