# Generated by Django 5.0.6 on 2026-10-05 15:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('actor_email', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('object_type', models.CharField(blank=True, default='', max_length=100)),
                ('object_id', models.CharField(blank=True, default='', max_length=255)),
                ('before_value', models.JSONField(blank=True, null=True)),
                ('after_value', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organisation', models.ForeignKey(blank=True, help_text='Tenant this action occurred in. SET_NULL so deleting an organisation never destroys audit history.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounts.organisation')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='audit_logs_action_391715_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_logs_object__457405_idx'), models.Index(fields=['actor_id', 'created_at'], name='audit_logs_actor_i_5bd818_idx'), models.Index(fields=['correlation_id'], name='audit_logs_correla_953e51_idx'), models.Index(fields=['organisation', 'created_at'], name='audit_logs_organis_41cc22_idx')],
            },
        ),
    ]
