# Generated by Django 5.0.6 on 2026-10-05 15:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCDocumentRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in the checklist')),
            ],
            options={
                'verbose_name': 'KYC Document Requirement',
                'verbose_name_plural': 'KYC Document Requirements',
                'db_table': 'kyc_document_requirements',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CreditReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_number', models.CharField(db_index=True, max_length=20)),
                ('bureau', models.CharField(db_index=True, max_length=50)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('risk_band', models.CharField(blank=True, default='', max_length=30)),
                ('total_monthly_obligations', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_outstanding_debt', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('worst_arrears_months', models.PositiveIntegerField(default=0)),
                ('has_defaults', models.BooleanField(default=False)),
                ('has_judgments', models.BooleanField(default=False)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('consented_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('pulled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pulled_credit_reports', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credit_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_status', models.CharField(blank=True, default='', max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_reviews', to='accounts.clientprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Review',
                'verbose_name_plural': 'KYC Reviews',
                'db_table': 'kyc_reviews',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creditor_name', models.CharField(max_length=200)),
                ('account_type', models.CharField(blank=True, default='', max_length=50)),
                ('account_number_masked', models.CharField(blank=True, default='', max_length=30)),
                ('monthly_installment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('original_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('opened_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='current', max_length=20)),
                ('arrears_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('months_in_arrears', models.PositiveIntegerField(default=0)),
                ('is_secured', models.BooleanField(default=False)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('credit_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_lines', to='kyc.creditreport')),
            ],
            options={
                'db_table': 'credit_trade_lines',
                'ordering': ['-months_in_arrears', '-outstanding_balance'],
            },
        ),
        migrations.AddIndex(
            model_name='creditreport',
            index=models.Index(fields=['user', 'expires_at'], name='credit_repo_user_id_4c102b_idx'),
        ),
        migrations.AddIndex(
            model_name='creditreport',
            index=models.Index(fields=['id_number'], name='credit_repo_id_numb_4df5c1_idx'),
        ),
    ]
