# Generated by Django 5.0.6 on 2026-10-05 15:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('account_number_masked', models.CharField(blank=True, default='', max_length=30)),
                ('statement_period_start', models.DateField(blank=True, null=True)),
                ('statement_period_end', models.DateField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('extraction_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_statements', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_statements', to='accounts.organisation')),
            ],
            options={
                'db_table': 'bank_statements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_date', models.DateField()),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', max_length=20)),
                ('category', models.CharField(blank=True, default='uncategorized', max_length=50)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_salary', models.BooleanField(default=False)),
                ('is_debit_order', models.BooleanField(default=False)),
                ('merchant_name', models.CharField(blank=True, default='', max_length=200)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('reviewer_corrected', models.BooleanField(default=False)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.bankstatement')),
            ],
            options={
                'db_table': 'bank_transactions',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.AddIndex(
            model_name='bankstatement',
            index=models.Index(fields=['client', 'processing_status'], name='bank_statem_client__a11cc1_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatement',
            index=models.Index(fields=['organisation', 'processing_status'], name='bank_statem_organis_a7bd8f_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['statement', 'transaction_date'], name='bank_transa_stateme_e3577d_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['category'], name='bank_transa_categor_77ab0a_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['is_salary'], name='bank_transa_is_sala_b47fb9_idx'),
        ),
    ]
